package com.jerryokafor.compose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0061a3)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcfe4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF006874)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF90f1ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f24)
val md_theme_light_tertiary = Color(0xFFb42900)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdacf)
val md_theme_light_onTertiaryContainer = Color(0xFF3d0700)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF1b1b1b)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1b1b1b)
val md_theme_light_surfaceVariant = Color(0xFFdfe3ec)
val md_theme_light_onSurfaceVariant = Color(0xFF42474e)
val md_theme_light_outline = Color(0xFF73777f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3033)

val md_theme_dark_primary = Color(0xFF9ccaff)
val md_theme_dark_onPrimary = Color(0xFF003259)
val md_theme_dark_primaryContainer = Color(0xFF00497e)
val md_theme_dark_onPrimaryContainer = Color(0xFFcfe4ff)
val md_theme_dark_secondary = Color(0xFF4fd8eb)
val md_theme_dark_onSecondary = Color(0xFF00363d)
val md_theme_dark_secondaryContainer = Color(0xFF004f59)
val md_theme_dark_onSecondaryContainer = Color(0xFF90f1ff)
val md_theme_dark_tertiary = Color(0xFFffb49e)
val md_theme_dark_onTertiary = Color(0xFF611100)
val md_theme_dark_tertiaryContainer = Color(0xFF8a1d00)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdacf)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1b)
val md_theme_dark_onBackground = Color(0xFFe2e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1b)
val md_theme_dark_onSurface = Color(0xFFe2e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF42474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7d0)
val md_theme_dark_outline = Color(0xFF8d9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1b)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)

val seed = Color(0xFF4183c4)
val error = Color(0xFFFF0000)


//Github Color
val githubCyanBlueAzure = Color(0xFF4078C0)
val githubApple = Color(0xFF6CC644)
val githubMahogany = Color(0xFFBD2C00)
val githubSpanishGray = Color(0xFF999999)
val githubGraniteGray = Color(0xFF666666)
val githubDarkCharcoal = Color(0xFF333333)

val githubBurntOrange = Color(0xFFC9510C)
val githubDarkLavender = Color(0xFF6E5494)
val githubLotion = Color(0xFFFAFAFA)
val githubCultured = Color(0xFFF5F5F5)
val githubBlack = Color(0xFF333333)


val githubOrgColor = Color(0xFFEB8B47)
val githubStarColor = Color(0xFFF1C747)
val githubRepoColor = Color(0xFF40434D)
val githubIssuesColor = Color(0xFF68CD67)
val githubPullRequestColor = Color(0xFF4385F7)
val githubDiscussionsColor = Color(0xFF6944BA)


